[project]
name = "2025-07-06-dev-containers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
]

[project.optional-dependencies]
analyze = [
    "pylint>=3.3.7",
]
test = [
    "pytest>=8.4.1",
]
