services:
  app:
    container_name: docker-to-rpm
    restart: unless-stopped
    privileged: true # should not be propagated to any other compose file. This is required for running podman inside a container
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/opt:cached
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      dev-net: # All of the containers will join the same Docker bridge network
        aliases:
          - dev-net
    environment:
      - PYTHONUNBUFFERED=1

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
networks:
  dev-net:
    name: dev-net
